### PR TITLE
Merge `main` into `target-allocator`

### PR DESCRIPTION
**Pull request by musa-asad**
*Description of changes:*
Merge `main` into `target-allocator`

*Testing:*
`make test` 
Screenshot 2024-09-18 at 4 43 08 PM

`make container`
Screenshot 2024-09-18 at 4 50 34 PM

`make ta-build-and-push`
Screenshot 2024-09-18 at 4 51 02 PM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by okankoAMZ** [comment]
How did you test it?

**Comment by musa-asad** [comment]
> How did you test it?

Updated description. I just ran `make test`.

**Review by okankoAMZ — COMMENTED** [review]
I tested these changes locally with 

- `make test`
- `make container`
- `make ta-build-and-push` 

they all seems to work fine.  
Could you update your description about these test and their outputs?

**Review by okankoAMZ — APPROVED** [review]

**Review by Paramadon — APPROVED** [review]
lgtm

**Pull request merged**
